### ISSUE TITLE
KML API is down

### ISSUE THREAD

**Issue by palewire** [datadesk/air-quality-index#17]
Here's what the agency says in response to my email:

> 
> Hi Ben,
> 
> Thank you for reaching out. We are aware of this issue and are investigating and I will let you know when it is resolved. In the meantime, if you require access to the AirNow contour maps in KML format, the full version of the KMLs can be found on files.airnowtech.org in either the "Today", "Yesterday", or individual date directories. I have listed links to the latest version of each below.
> 
>     [Latest O3 KML](https://s3-us-west-1.amazonaws.com//files.airnowtech.org/airnow/today/cur_aqi_ozone.kml)
>     [Latest PM2.5 KML](https://s3-us-west-1.amazonaws.com//files.airnowtech.org/airnow/today/cur_aqi_pm25.kml)
>     [Latest combined AQI KML](https://s3-us-west-1.amazonaws.com//files.airnowtech.org/airnow/today/cur_aqi_combined.kml)
> 
> -Marcus
>  
> Marcus Hylton, AirNow DMC Lead
> [marcus.hylton@TDEnviro.com](mailto:marcus.hylton@TDEnviro.com)  |  [www.TDEnviro.com](http://www.tdenviro.com/)  
> TD Environmental Services, LLC

**Comment by palewire** [comment]
I've updated the library to pull from the PM2.5 KML above instead. It seems to be working. You can see the result [here](https://github.com/datadesk/air-quality-index/blob/main/data/air-quality.geojson). The main issue with the upgrade seems to be that the styleUrl column will contain the classification of the areas, and it will use a hashtag system that's different from what we had in the past.

![Screenshot from 2024-07-29 12-31-53](https://github.com/user-attachments/assets/528962b2-349c-4f6a-8892-667c44212025)

**Comment by palewire** [comment]
Since what we have now is broken, for the foreseeable future, I'm going to cut an "major dot" upgrade to the library with this patch. Besides working, the other upside here is that we no longer need an API key.

**Comment by vnessamartinez** [comment]
Thank you for documenting this and making the fix, @palewire!
